version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/exome_p/
    ports:
      - 8000:8000
    env_file:
      - exome_p/.env
  db:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=geneticist
        - POSTGRES_PASSWORD=B1oAk61Ccn9fhiqJ
        - POSTGRES_DB=exome_p
volumes:
  postgres_data:
