# Generated by Django 3.1.2 on 2020-10-19 16:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import files_uploading.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('genotype', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AllelesRecord',
            fields=[
                ('record', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('number', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MitochondriaHaplogroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haplogroup', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('cypher', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Undefined')], default='U', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField()),
                ('alternative_allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_to_snp', to='files_uploading.allele')),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_uploading.chromosome')),
                ('reference_allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_to_snp', to='files_uploading.allele')),
            ],
        ),
        migrations.CreateModel(
            name='VCFFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='raw_data/vcf/', validators=[files_uploading.validators.check_vcf_format, django.core.validators.FileExtensionValidator(allowed_extensions=['vcf', 'vcf.gz', 'bcf'])])),
            ],
        ),
        migrations.CreateModel(
            name='YHaplogroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haplogroup', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alleles', models.ManyToManyField(to='files_uploading.Allele')),
                ('alleles_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.allelesrecord')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_uploading.sample')),
                ('snp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.snp')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='Y_haplogroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.yhaplogroup'),
        ),
        migrations.AddField(
            model_name='sample',
            name='mitochondrial_haplogroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.mitochondriahaplogroup'),
        ),
        migrations.AddField(
            model_name='sample',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.nationality'),
        ),
        migrations.AddField(
            model_name='sample',
            name='vcf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.vcffile'),
        ),
    ]
