# Generated by Django 3.1.2 on 2020-10-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_uploading', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='snp',
            unique_together={('chromosome', 'position', 'reference_allele', 'alternative_allele')},
        ),
    ]
