# Generated by Django 3.1.2 on 2020-10-13 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import files_uploading.validators


class Migration(migrations.Migration):

    dependencies = [
        ('files_uploading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('variant', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AllelesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('number', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MitochondriaHaplogroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haplogroup', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alternative_allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ALT', to='files_uploading.allele')),
                ('reference_allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REF', to='files_uploading.allele')),
            ],
        ),
        migrations.CreateModel(
            name='YHaplogroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haplogroup', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='vcffile',
            name='file',
            field=models.FileField(upload_to='raw_data/vcf/', validators=[files_uploading.validators.check_vcf_format, django.core.validators.FileExtensionValidator(allowed_extensions=['vcf', 'vcf.gz', 'bcf'])]),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('alleles_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.allelesrecord')),
                ('chromosome_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_uploading.chromosome')),
                ('snp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.snp')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cypher', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Undefined')], default='U', max_length=15)),
                ('Y_haplogroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.yhaplogroup')),
                ('mitochondrial_haplogroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.mitochondriahaplogroup')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.nationality')),
            ],
        ),
    ]
