# Generated by Django 3.1.2 on 2020-10-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_uploading', '0002_auto_20201013_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='vcf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_uploading.vcffile'),
        ),
    ]
