# Generated by Django 3.1.2 on 2020-10-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_uploading', '0003_sample_vcf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allelesrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='allelesrecord',
            name='record',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
